name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip wget

          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK CLEAN
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME

          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-*.zip -d android-sdk/cmdline-tools

          mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest

          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin

          yes | sdkmanager --licenses || true

          sdkmanager \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"

      - name: FORCE Buildozer to NOT use 37
        run: |
          echo "android.build_tools_version = 34.0.0" >> buildozer.spec
          echo "p4a.branch = stable" >> buildozer.spec

          export BUILDOZER_WARN_ON_ROOT=0
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_HOME=$HOME/android-sdk

      - name: Build APK
        run: |
          export BUILDOZER_WARN_ON_ROOT=0
          export P4A_NO_BINREPO_UPDATE=1
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_HOME=$HOME/android-sdk

          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
